import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { createDatabase, schema } from "@obliq/database";
import {
  addVendorDestination,
  createControlledRegtestQuote,
  createDefaultPolicy,
  createObligation,
  createVendor,
  decideApproval,
  evaluateObligationControls,
  evaluateSettlementReadiness,
  getControlView,
  prepareSettlementIntent,
  requestExternalSignature,
  verifyDestinationManually,
} from "@obliq/database/repositories";
import { eq } from "drizzle-orm";

const databaseUrl = process.env.DATABASE_URL;
const receiverFile = process.env.OBLIQ_TRACER_RECEIVER_FILE;
const outputFile = process.env.OBLIQ_TRACER_HANDOFF_FILE;
if (!databaseUrl || !receiverFile || !outputFile)
  throw new Error(
    "DATABASE_URL, OBLIQ_TRACER_RECEIVER_FILE and OBLIQ_TRACER_HANDOFF_FILE are required",
  );

const response = JSON.parse(await readFile(receiverFile, "utf8")) as {
  address?: string;
  result?: { address?: string } | string;
};
const receiver =
  response.address ??
  (typeof response.result === "string"
    ? response.result
    : response.result?.address);
if (!receiver?.startsWith("uregtest1"))
  throw new Error("A regtest Unified Address is required");

const connection = createDatabase(databaseUrl);
try {
  const organizationId = randomUUID();
  const ownerId = randomUUID();
  const financeId = randomUUID();
  const treasuryId = randomUUID();
  await connection.db
    .insert(schema.organizations)
    .values({ id: organizationId, name: "Phase 4 tracer" });
  await connection.db.insert(schema.users).values([
    {
      id: ownerId,
      email: `${ownerId}@phase4.obliq.test`,
      displayName: "Tracer requester",
    },
    {
      id: financeId,
      email: `${financeId}@phase4.obliq.test`,
      displayName: "Tracer finance",
    },
    {
      id: treasuryId,
      email: `${treasuryId}@phase4.obliq.test`,
      displayName: "Tracer treasury",
    },
  ]);
  await connection.db.insert(schema.memberships).values([
    { organizationId, userId: ownerId, role: "OWNER" },
    { organizationId, userId: financeId, role: "FINANCE" },
    { organizationId, userId: treasuryId, role: "TREASURY" },
  ]);
  const owner = { organizationId, userId: ownerId };
  const vendor = await createVendor(connection.db, owner, {
    legalName: "Phase 4 Test Vendor",
    displayName: "Phase 4 Test Vendor",
  });
  const destination = await addVendorDestination(
    connection.db,
    owner,
    vendor.id,
    { network: "ZCASH", receiver },
  );
  if (!destination) throw new Error("Destination creation failed");
  await verifyDestinationManually(
    connection.db,
    { organizationId, userId: treasuryId },
    destination.id,
    "Isolated tracer ceremony",
    "Receiver generated by the read-only tracer account",
  );
  const obligation = await createObligation(connection.db, owner, {
    vendorId: vendor.id,
    type: "VENDOR_INVOICE",
    reference: `P4-${Date.now()}`,
    currency: "USD",
    amount: "250.00",
    dueDate: "2026-12-31",
    description: "Phase 4 application-bound settlement tracer",
  });
  await createDefaultPolicy(connection.db, owner);
  await evaluateObligationControls(connection.db, owner, obligation.id);
  const control = await getControlView(
    connection.db,
    organizationId,
    obligation.id,
  );
  for (const requirement of control.requirements) {
    const approver = requirement.role === "TREASURY" ? treasuryId : financeId;
    for (let index = 0; index < requirement.requiredCount; index += 1)
      await decideApproval(
        connection.db,
        { organizationId, userId: approver },
        requirement.id,
        "APPROVE",
        "Reviewed for Phase 4 tracer",
      );
  }
  const readiness = await evaluateSettlementReadiness(
    connection.db,
    owner,
    obligation.id,
  );
  if (!readiness?.ready) throw new Error("Phase 2 readiness did not pass");
  const quote = await createControlledRegtestQuote(connection.db, owner, {
    obligationId: obligation.id,
    zatoshiAmount: 25_000_000n,
    idempotencyKey: randomUUID(),
    expiresAt: new Date(Date.now() + 4 * 60 * 60_000),
  });
  const intent = await prepareSettlementIntent(connection.db, owner, {
    quoteId: quote.id,
    idempotencyKey: randomUUID(),
    requiredConfirmations: 3,
  });
  if (!intent) throw new Error("Settlement intent creation failed");
  const [settlement] = await connection.db
    .select()
    .from(schema.settlements)
    .where(eq(schema.settlements.intentId, intent.id))
    .limit(1);
  if (!settlement) throw new Error("Settlement creation failed");
  const signerRequestId = randomUUID();
  const handoff = await requestExternalSignature(
    connection.db,
    owner,
    settlement.id,
    signerRequestId,
  );
  if (!handoff) throw new Error("Signer handoff creation failed");
  await writeFile(
    outputFile,
    JSON.stringify({
      organizationId,
      actorId: ownerId,
      obligationId: obligation.id,
      settlementId: settlement.id,
      signerRequestId,
      ...handoff,
    }),
    { mode: 0o600 },
  );
  console.log(
    JSON.stringify({
      organizationId,
      obligationId: obligation.id,
      settlementId: settlement.id,
      intentHash: intent.intentHash,
      state: "AWAITING_SIGNATURE",
    }),
  );
} finally {
  await connection.close();
}
